const eventCards = [
  {
    id: 'shipment-water-filter-redirect',
    family: 'system-transport',
    minDay: 1,
    truth: 'malicious',
    subject: '【紧急】你的净水滤芯已到达中转站',
    sender: '北境救援物流 <dispatch@north-relief-logistics.co>',
    time: '03:17',
    paragraphs: [
      '指挥官，你预订的净水滤芯已经抵达东侧中转站。',
      '车辆只会保留 15 分钟；请立即确认领取，否则物资将转交给其他避难所。',
      '确认领取：north-relief-logistics.co/claim/2048',
    ],
    clue: '可信供应商域名是 northrelief-logistics.co。邮件域名多了一个连字符。',
    sandbox: ['打开隔离浏览器…', '发现跳转：north-relief-logistics.co → northrelief-logistics-login.co', '目标页面请求避难所通行凭证。'],
    outcomes: {
      accept: { kind: 'accepted', title: '避难所通行凭证已泄露', message: '伪造页面尝试接入避难所网络。完整性 -25%，网络中继器受损。', learning: '紧急物资通知也要核对完整域名，而不是只看显示名称。', resources: { integrity: -25 }, facility: 'relay', facilityState: 'damaged', impact: '账户会话被盗，网络中继器出现异常调用。', nightThreat: 'unauthorized-requisition' },
      report: { kind: 'secured', title: '仿冒运输通知已阻断', message: '你截获了钓鱼链路，避难所获得 6 点情报。', learning: '相似域名与人为制造的时间压力，是典型的运输钓鱼组合。', resources: { intel: 6 }, facility: 'radio', facilityState: 'upgraded', impact: '无线电站获得新的域名过滤规则。', report: '识别到仿冒域名、二次跳转与凭证索取。' },
    },
  },
  {
    id: 'shipment-ration-crate',
    family: 'system-transport',
    minDay: 1,
    truth: 'legitimate',
    subject: '【系统运输】第 07 批口粮箱已入库',
    sender: '避难所联合运输 <dispatch@relay-union.org>',
    time: '08:42',
    paragraphs: ['第 07 批口粮箱已抵达西门。订单编号与指挥室记录一致。', '请在日落前确认入库；本次运输不需要重新登录或额外授权。'],
    clue: '订单编号、发件域名与指挥室的运输台账一致；邮件没有索取凭证。',
    sandbox: ['读取运输签名…', '订单编号与本地台账匹配。', '未发现跳转、附件或凭证请求。'],
    outcomes: {
      accept: { kind: 'secured', title: '口粮箱已安全入库', message: '仓库获得 18 点物资，今晚的补给压力降低。', learning: '真实运输通知也会有期限；关键在于它能否被独立记录核验。', resources: { supplies: 18 }, facility: 'warehouse', facilityState: 'upgraded', impact: '仓库完成一次安全入库。' },
      report: { kind: 'accepted', title: '真实补给被错误拦截', message: '口粮运输超时离开，避难所错失 18 点物资。', learning: '不要因为邮件紧急就举报；应同时检查订单记录、发件域名和请求内容。', resources: { supplies: -6 }, impact: '运输信誉下降，补给车没有等待到确认。' },
    },
  },
  {
    id: 'shipment-medical-attachment',
    family: 'system-transport',
    minDay: 3,
    truth: 'malicious',
    subject: '【医疗优先】止血包清单需要签收',
    sender: '联合医疗调配 <manifest@med-aid-center.net>',
    time: '12:09',
    paragraphs: ['一批止血包正在等待签收。请下载随附的“库存同步表”并在本机打开。', '若未在一小时内完成，物资将被重新分配。'],
    clue: '医疗中心从不要求在本机打开运输附件；正式清单只会出现在运输台账。',
    sandbox: ['打开隔离附件…', '附件试图请求终端的设备控制权限。', '隔离环境已阻断异常启动行为。'],
    outcomes: {
      accept: { kind: 'accepted', title: '伪造清单感染了终端', message: '设备完整性 -18%，医疗站的夜间状态监测将不稳定。', learning: '来自可信主题的附件同样需要核验；不要在主终端打开未知文件。', resources: { integrity: -18 }, facility: 'clinic', facilityState: 'damaged', impact: '医疗站终端出现异常进程。', nightThreat: 'device-disruption' },
      report: { kind: 'secured', title: '恶意附件已隔离', message: '避难所获得 7 点情报，医疗终端未受影响。', learning: '沙盒的价值在于观察行为，而不是把附件当作真实文件执行。', resources: { intel: 7 }, impact: '医疗站保持离线安全状态。', report: '伪造医疗运输附件请求了不必要的终端权限。' },
    },
  },
  {
    id: 'shipment-water-purifier',
    family: 'system-transport',
    minDay: 4,
    truth: 'legitimate',
    subject: '【施工许可】便携净水器组件已抵达',
    sender: '水源修复署 <field-kits@waterworks.org>',
    time: '10:31',
    paragraphs: ['你申请的便携净水器组件已抵达南侧中转站。施工许可编号可在指挥室档案中核验。', '确认后，净水设施用地将开放部署。'],
    clue: '许可编号与申请记录一致，收件人不是要求交出账号，而是确认已有的施工许可。',
    sandbox: ['核对施工许可…', '编号与基地申请档案一致。', '组件清单仅包含净水器与备用滤芯。'],
    outcomes: {
      accept: { kind: 'secured', title: '净水器蓝图已解锁', message: '净水设施用地现在可以建设；获得 1 组备用滤芯。', learning: '高价值物资更应以独立的许可、订单和收货记录相互印证。', resources: { supplies: 8 }, unlockExpansion: 'water', impact: '净水设施用地获得施工许可。' },
      report: { kind: 'accepted', title: '净水器组件被退回', message: '你错过了施工许可窗口，净水设施仍无法部署。', learning: '安全判断不是一味拒绝，而是在可验证的证据存在时果断执行。', impact: '净水设施用地仍处于未开发状态。' },
    },
  },
  {
    id: 'market-seed-order',
    family: 'world-market',
    minDay: 2,
    truth: 'legitimate',
    subject: '世界交易：耐旱种子订单等待放行',
    sender: '灰谷种子合作社 <orders@grayvalley-seeds.market>',
    time: '09:18',
    paragraphs: ['你在世界交易预订的耐旱种子已备货。请确认交易单号 GV-218 与收货地为避难所 07。', '放行后，种子将交由西门商队运送。'],
    clue: '交易单号、收货地与玩家自己的市场订单一致；邮件没有要求修改付款账户。',
    sandbox: ['读取交易签名…', '订单 GV-218 与市场账本匹配。', '收货地与避难所 07 一致。'],
    outcomes: {
      accept: { kind: 'secured', title: '耐旱种子已收货', message: '获得 8 份耐旱种子。菜园蓝图到位后即可开始种植。', learning: '市场邮件要核对自己的订单与收货信息，而不只是相信卖家名称。', resources: { seeds: 8 }, impact: '仓库保存了第一批耐旱种子。' },
      report: { kind: 'accepted', title: '真实市场订单被取消', message: '种子被合作社重新上架，预付款中的 5 枚金币无法追回。', learning: '订单本身可被独立核验时，应避免将真实交易误判为威胁。', resources: { coins: -5 }, impact: '市场信誉轻微下降。' },
    },
  },
  {
    id: 'market-address-change',
    family: 'world-market',
    minDay: 2,
    truth: 'malicious',
    subject: '世界交易：请立即更新商队收货地址',
    sender: '世界交易结算 <billing@world-markets.support>',
    time: '16:44',
    paragraphs: ['你的商队订单因“围栏损坏”无法送达。请使用下面页面更新收货地址并重新授权付款。', '未操作的订单将在 10 分钟后自动取消。'],
    clue: '世界交易使用 market.world，不使用 world-markets.support；订单记录中也没有围栏损坏提示。',
    sandbox: ['打开隔离交易页面…', '页面要求输入完整付款口令。', '订单号与市场账本不匹配。'],
    outcomes: {
      accept: { kind: 'accepted', title: '交易资金被转移', message: '金币 -14，攻击者还获得了下一次市场请求的伪造权限。', learning: '任何要求重新授权付款或修改收货地的交易，都应回到原订单核验。', resources: { coins: -14 }, impact: '市场账户出现未经授权的付款记录。', nightThreat: 'market-drain' },
      report: { kind: 'secured', title: '伪造结算页已举报', message: '你保住了交易资金，并获得 6 点情报。', learning: '交易骗局常利用临时地址变更和倒计时迫使玩家绕过账本。', resources: { intel: 6 }, impact: '市场账户已标记该伪造结算域名。', report: '伪造市场页面索取付款口令，且订单不存在。' },
    },
  },
  {
    id: 'market-radio-parts',
    family: 'world-market',
    minDay: 3,
    truth: 'legitimate',
    subject: '世界交易：无线电备用线圈到货',
    sender: '旧城电子摊 <orders@oldcity-electronics.market>',
    time: '13:26',
    paragraphs: ['你订购的无线电备用线圈已由南门商队送达。订单金额与市场托管记录一致。', '确认收货后，维修组可用于加固无线电站。'],
    clue: '卖家域名、托管金额和玩家订单一致；交易不需要离开世界市场的结算页。',
    sandbox: ['核对托管记录…', '订单金额与市场托管一致。', '线圈序列号在商队清单内。'],
    outcomes: {
      accept: { kind: 'secured', title: '无线电线圈已验收', message: '物资 +6，无线电站的通讯稳定性提高。', learning: '真实交易的付款与收货信息应能在独立的托管记录中找到。', resources: { supplies: 6 }, facility: 'radio', facilityState: 'upgraded', impact: '无线电站换装了备用线圈。' },
      report: { kind: 'accepted', title: '维修零件被拒收', message: '商队带走线圈，下一次无线电维修将更困难。', learning: '对真实订单误报会失去建设机会；先看托管记录再判断。', impact: '无线电站失去一次维修机会。' },
    },
  },
  {
    id: 'market-refund-lure',
    family: 'world-market',
    minDay: 3,
    truth: 'malicious',
    subject: '世界交易：你的退款已获批准',
    sender: '世界交易退款中心 <refund@market-world-recovery.net>',
    time: '19:03',
    paragraphs: ['你未收到的订单已获退款。请通过“快速领取”页面确认身份，金币将在五分钟内到账。', '逾期后退款会自动冻结。'],
    clue: '玩家没有未结退款；退款中心的域名也不属于世界交易。',
    sandbox: ['加载退款页面…', '页面伪造了余额面板并请求市场口令。', '本地账本中没有对应退款单。'],
    outcomes: {
      accept: { kind: 'accepted', title: '假退款清空了部分余额', message: '金币 -11，市场终端被标记为高风险。', learning: '先确认自己是否真的有退款；不存在的订单不能产生合法退款。', resources: { coins: -11 }, impact: '市场余额出现异常扣款。', nightThreat: 'market-drain' },
      report: { kind: 'secured', title: '退款诱饵已阻断', message: '你避免了资金损失，获得 5 点情报。', learning: '攻击者经常用“你会得到钱”取代“你会失去钱”来降低警惕。', resources: { intel: 5 }, impact: '市场终端加入退款域名黑名单。', report: '退款页面对应的订单不存在，并索取市场口令。' },
    },
  },
  {
    id: 'people-gardener-arrival',
    family: 'people',
    minDay: 2,
    truth: 'legitimate',
    subject: '西门来信：携带种子的农艺员请求收留',
    sender: '白桦营地联络员 <liaison@birch-camp.net>',
    time: '11:50',
    paragraphs: ['农艺员林禾与两名护送者在西门等待。他们携带耐旱种子与菜园图纸，要求以安全住宿交换劳作。', '白桦营地的旧盟约编号可在无线电档案中核验。'],
    clue: '联络员、盟约编号和无线电档案一致；请求的是有限的住宿安排，而不是基地口令。',
    sandbox: ['核对盟约编号…', '白桦营地与避难所 07 有既有联络记录。', '人员清单与护送频道一致。'],
    outcomes: {
      accept: { kind: 'secured', title: '菜园蓝图已解锁', message: '农艺员加入基地，菜园用地可以开始建设。', learning: '涉及人员的请求也应通过既有关系与独立通信记录核验。', resources: { seeds: 4 }, unlockExpansion: 'garden', impact: '农艺员带来了菜园施工图与种子。' },
      report: { kind: 'accepted', title: '可信幸存者被拒之门外', message: '农艺员离开西门，菜园蓝图暂时无法获得。', learning: '社交工程并不意味着所有陌生求助都是骗局；证据链才是判断依据。', impact: '菜园用地仍处于未开发状态。' },
    },
  },
  {
    id: 'people-relief-scout',
    family: 'people',
    minDay: 3,
    truth: 'malicious',
    subject: '紧急求助：请开启东侧闸门接收伤员',
    sender: '曙光临时营地 <help@dawn-relief.camp>',
    time: '22:14',
    paragraphs: ['我们有三名伤员在东侧围栏外，请立刻开启闸门并发送基地照明与巡逻路线。', '若不立即答复，伤员可能撑不过今晚。'],
    clue: '曙光营地不在已知盟友名单内；邮件要求提供巡逻路线和防线细节，超出了求救所需信息。',
    sandbox: ['核对盟友通讯簿…', '未找到曙光临时营地的已验证联络记录。', '请求中包含不必要的防线与照明信息。'],
    outcomes: {
      accept: { kind: 'accepted', title: '外围防线位置被泄露', message: '攻击者获得东侧巡逻情报；今晚东侧防线将承受额外压力。', learning: '求救信息也要遵循最小披露原则；不要因为紧急而交出防御细节。', impact: '东侧扩建地块附近出现陌生侦察信号。', nightThreat: 'location-exposed' },
      report: { kind: 'secured', title: '伪造求救已识破', message: '你没有暴露巡逻路线，并获得 8 点情报。', learning: '真实求救应能由盟友档案、地点与有限请求共同支持。', resources: { intel: 8 }, impact: '东侧防线提高了警戒等级。', report: '未知营地索取了与救援无关的巡逻和照明信息。' },
    },
  },
  {
    id: 'maintenance-radio-patch',
    family: 'maintenance',
    minDay: 2,
    truth: 'legitimate',
    subject: '维护窗口：无线电域名过滤规则更新',
    sender: '避难所网络维护 <patch@relay-union.org>',
    time: '06:35',
    paragraphs: ['无线电站的过滤规则有可用更新。更新包已在本地维护通道排队，无需下载附件。', '确认维护窗口后，系统将在十分钟内切换规则。'],
    clue: '维护请求只要求确认既有维护窗口，不要求下载文件、输入密码或跳往外部站点。',
    sandbox: ['检查维护通道…', '更新已位于本地维护队列。', '签名来自避难所网络维护密钥。'],
    outcomes: {
      accept: { kind: 'secured', title: '过滤规则已更新', message: '无线电站升级，获得 4 点情报。', learning: '合法维护通常发生在受控渠道内，而不是要求绕过系统下载。', resources: { intel: 4 }, facility: 'radio', facilityState: 'upgraded', impact: '无线电站开始拦截已知仿冒域名。' },
      report: { kind: 'accepted', title: '维护窗口被错过', message: '过滤规则没有更新，基地暂时失去一次防护提升。', learning: '更新通知需要核对来源与渠道，不应仅因“维护”二字而拒绝。', impact: '无线电站维持旧版过滤规则。' },
    },
  },
  {
    id: 'maintenance-relay-patch',
    family: 'maintenance',
    minDay: 3,
    truth: 'malicious',
    subject: '紧急修复：请立即安装中继器稳定补丁',
    sender: '网络维护响应组 <urgent@relay-service-secure.org>',
    time: '01:48',
    paragraphs: ['检测到网络中继器即将过热。请下载“稳定补丁”并以管理员模式运行，否则今晚通讯会完全中断。', '此修复不在常规维护窗口内。'],
    clue: '未知维护域名、要求下载执行文件、刻意绕过既有维护窗口，三者同时出现。',
    sandbox: ['打开隔离更新包…', '更新包试图替换中继器的远程控制配置。', '隔离环境阻止了设备配置写入。'],
    outcomes: {
      accept: { kind: 'accepted', title: '中继器控制权被篡改', message: '完整性 -20%，夜晚会出现设备干扰。', learning: '紧急补丁不能跳过受控维护渠道；越要求管理员权限，越应谨慎核验。', resources: { integrity: -20 }, facility: 'relay', facilityState: 'damaged', impact: '网络中继器的远程配置被篡改。', nightThreat: 'device-disruption' },
      report: { kind: 'secured', title: '伪造维护包已隔离', message: '你阻断了设备控制篡改，获得 8 点情报。', learning: '真实维护会留下可核验的窗口、签名和内部渠道。', resources: { intel: 8 }, impact: '中继器保持受控维护状态。', report: '伪造补丁试图改写中继器的远程控制配置。' },
    },
  },
];

function getEligibleEventCards(day) {
  return eventCards.filter((card) => card.minDay <= day);
}
